group=kiocg.com
mcVersion=26.1.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.1.2
paperRef=02ec8e9585c44d0ccbdf28495890308e25c045cb

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808