group=kiocg.com
#version=1.21.11-R0.1-SNAPSHOT
apiVersion=26.1.1
mcVersion=26.1.1
paperRef=4aeb7aed6972ad84a2888d2adce86b08148b23fd

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808